language: python
python:
  - '3.6'
install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
  - conda install --channel defaults conda-build=3.18.11 conda-verify=3.1.1
  - conda config --add channels conda-forge
  - conda build --quiet .
  - conda create --use-local --name osewb ose-workbench-platform
  - conda activate osewb
  - export PYTHONPATH=$PYTHONPATH:$CONDA_PREFIX/lib
script:
    - pytest --cov osewb/ tests/
after_success:
    - coveralls
