{% set data = load_setup_py_data(setup_file='./setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.name }}
  version: {{ data.version }}

source:
  path: ../ose-workbench-platform

build:
  number: 0
  entry_points:
    - osewb = osewb.osewb:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - freecad ==0.18.4

    # -------------------
    # Source Dependencies
    # -------------------
    - cookiecutter ==1.7.2
    - jinja2-time ==0.2.0
    - pip
    - python

    # -----------------
    # Docs Dependencies
    # -----------------
    - sphinx ==3.0.2
    - sphinx_rtd_theme ==0.4.3

    # -----------------
    # Test Dependencies
    # -----------------
    - coverage==5.1
    - coveralls==2.0.0
    - pytest==5.4.3
    - pytest-cov==2.9.0

  run:
    - freecad ==0.18.4

    # -------------------
    # Source Dependencies
    # -------------------
    - cookiecutter ==1.7.2
    - jinja2-time ==0.2.0
    - pip
    - python

    # -----------------
    # Docs Dependencies
    # -----------------
    - sphinx ==3.0.2
    - sphinx_rtd_theme ==0.4.3

    # -----------------
    # Test Dependencies
    # -----------------
    - coverage ==5.1
    - coveralls ==2.0.0
    - pytest ==5.4.3
    - pytest-cov ==2.9.0

test:
  imports:
    - osewb
    - osewb.docs
    - osewb.docs.ext
  commands:
    - osewb --help

about:
  home: https://github.com/gbroques/ose-workbench-platform
  license: GNU General Public License v2 or later (GPLv2+)
  license_file: LICENSE
  summary: "Common platform for developing Open Source Ecology (OSE) workbenches."
  doc_url: https://ose-workbench-platform.readthedocs.io/en/latest/
  dev_url: https://github.com/gbroques/ose-workbench-platform

extra:
  recipe-maintainers:
    - gbroques
