{% set data = load_setup_py_data(setup_file='./setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.name }}
  version: {{ data.version }}

source:
  path: ../ose-workbench-platform

build:
  number: 0
  entry_points:
    - osewb = osewb.osewb:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - freecad ==0.19.alpha2  # Also in environment.yml and CONTRIBUTING.md
    {% for package in data.install_requires %}
    # sphinx-rtd-theme PyPi package is named sphinx_rtd_theme on conda
    {% if package.startswith('sphinx-rtd-theme') %}
    - {{ package | replace('-', '_') }}
    {% else %}
    - {{ package }}
    {% endif %}
    {% endfor %}

test:
  imports:
    - osewb
    - osewb.docs
    - osewb.docs.ext
  commands:
    - osewb --help

about:
  home: https://github.com/gbroques/ose-workbench-platform
  license: GNU General Public License v2 or later (GPLv2+)
  license_file: LICENSE
  summary: "Common platform for developing Open Source Ecology (OSE) workbenches."
  doc_url: https://ose-workbench-platform.readthedocs.io/en/latest/
  dev_url: https://github.com/gbroques/ose-workbench-platform

extra:
  recipe-maintainers:
    - gbroques
