version: '3'
services:
  test:
    container_name: {{ cookiecutter.base_package }}-test
    image: oseworkbench-test-image
    build:
      context: https://github.com/gbroques/ose-workbench-platform.git#v0.1.0a5
      dockerfile: test.Dockerfile
    volumes:
      - ./:/var/app
    network_mode: bridge
